server:
 port: 8082

resilience4j:
  retry:
    retry-aspect-order: 2
    instances:
      gatewayRetry:
        max-attempts: 5
        wait-duration: 10s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
         - org.springframework.web.client.RestClientException
        ignore-exceptions:
         -  com.siemens.resilience4jdemo.exceptions.IgnoreException
  circuitbreaker:
    circuit-breaker-aspect-order: 1
    instances:
      gatewayCircuitBreaker:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 5
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 60 
        failure-rate-threshold: 60

serviceUrl: http://localhost:8765/customers/v1.0
alternativeServiceUrl: http://localhost:7074/customers/v1.0
